aaronmallen/activeinteractor

- .codeclimate.yml
Exclude config files from codeclimate
resolves #9
> exclude config files from codeclimate

- activeinteractor.gemspec
Added documentation_uri and wiki_uri to gemspec metadata
> Added documentation_uri and wiki_uri to gemspec metadata

- lib/active_interactor/organizer.rb
fixed #14 NoMethodError (undefined method merge for #<ActiveInteractor::Context::Base>)
fixes #14
> fixed #14 NoMethodError

- .travis.yml
> Allow travis to build tags

- .travis.yml
properly escape regex for travis
> properly escape regex for travis

- lib/active_interactor/base.rb
- lib/active_interactor/interactor/execution.rb
- lib/active_interactor/organizer.rb
- spec/active_interactor/interactor/worker_spec.rb
- spec/active_interactor/organizer_spec.rb
- spec/support/helpers/factories.rb
- spec/support/shared_exaples/interactor_lint.rb
Increase test coverage for project
resolve #5 
resolve #6
> Increase test coverage

- CHANGELOG.md
- lib/active_interactor/configuration.rb
- lib/rails/generators/active_interactor.rb
- lib/rails/generators/active_interactor/install_generator.rb
- lib/rails/generators/interactor/interactor_generator.rb
- lib/rails/generators/interactor/organizer_generator.rb
- lib/rails/generators/interactor/rspec_generator.rb
- lib/rails/generators/interactor/test_unit_generator.rb
- lib/rails/generators/templates/initializer.rb
- spec/active_interactor/configuration_spec.rb
Allow the directory interactors are generated in to be configurable
resolves #21
> Allow the directory interactors are generated in to be configurable

- lib/active_interactor.rb
- lib/active_interactor/configuration.rb
- lib/active_interactor/interactor/callbacks.rb
- lib/active_interactor/interactor/execution.rb
- lib/active_interactor/interactor/worker.rb
- lib/active_interactor/organizer.rb
Ensure documentation is accurate
resolves #12
> documentation audit

- CHANGELOG.md
- README.md
- lib/active_interactor/organizer.rb
implement each_perform callbacks on organizers
resolves #24
> Implement each_perform callbacks on organizers

- CHANGELOG.md
- README.md
Small fixes to `README.md` and `CHANGELOG.md`
> fixed issues with README and CHANGELOG

- CHANGELOG.md
Fixed pull request links in changelog :derp:
> Fixed pull request links in changelog

- .codeclimate.yml
Disable git-legal for codeclimate
fixes #31
> Disable git-legal for codeclimate

- lib/active_interactor/context.rb
- lib/active_interactor/context/attributes.rb
- lib/active_interactor/interactor/worker.rb
- lib/active_interactor/organizer.rb
lowered method complexity and enforced single responsibility
> lowered method complexity and enforced single responsibility

- Gemfile.lock
- lib/active_interactor/context.rb
- lib/active_interactor/context/attributes.rb
- lib/active_interactor/interactor/worker.rb
- lib/active_interactor/organizer.rb
Here is everything you need to know about this update. Please take a good look at what changed and the test results before merging this pull request.
<details>
<summary>Release Notes</summary>
<h4>12.3.3 (from changelog)</h4>
<blockquote><h4>
<a href="#bug-fixes"></a>Bug fixes</h4>
<ul><li>
<p>Use the application's name in error message if a task is not found.
Pull Request <a href="https://bounce.depfu.com/github.com/ruby/rake/pull/303">#303</a> by tmatilai</p>
</li></ul>
<h4>
<a href="#enhancements"></a>Enhancements:</h4>
<ul><li>
<p>Use File.open explicitly.</p>
</li></ul></blockquote>
<p><em>Does any of this look wrong? <a href="https://depfu.com/packages/rubygem/rake/feedback">Please let us know.</a></em></p>
</details>
<details>
<summary>Commits</summary>
<p><a …
> Update rake: 12.3.2 → 12.3.3 (patch)

- README.md
- lib/rails/generators/active_interactor/install_generator.rb
- lib/rails/generators/templates/initializer.erb
add directory argument to install generator
resolve #53
> add directory argument to install generator

- CHANGELOG.md
- Gemfile.lock
- lib/active_interactor/version.rb
- [#61] Ensure `Organizer` accurately reports context success
> v0.1.7 release canidate

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
Update Pull Request and Issue templates
> update github templates

- .github/workflows/ci.yml
ensure `CC_TEST_REPORTER_ID` is available durning the entire testing process
> CC_TEST_REPORTER_ID Env fix

- .github/workflows/deploy.yml
Apply same fix introduced in #78 to the `deploy` action
- see #78
> add env var to deploy action

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- Gemfile
- Gemfile.lock
- README.md
- spec/spec_helper.rb
> add codacy to the project

- .github/workflows/ci.yml
Set `CODACY_RUN_LOCAL` to true to report coverage to codacy.
> fix codacy reporter

- CHANGELOG.md
- lib/active_interactor/version.rb
v1.0.0-beta.1 release canidate
- `ActiveInteractor.logger=`
- `ActiveInteractor::Base#dup`
- `ActiveInteractor::Context::Loader`
- `ActiveInteractor::Error::InvalidContextClass`
- `ActiveInteractor::Interactor::Context#context_fail!`
- `ActiveInteractor::Interactor::Context#context_rollback!`
- `ActiveInteractor::Interactor::Context.contextualize_with`
- `ActiveInteractor::Interactor::Context#finalize_context!`
- `ActiveInteractor::Context::Attributes.attributes` now excepts arguments for attributes
- `ActiveInteractor::Generators` various improvements to rails generators
- `ActiveInteractor::Interactor::Context.context_class` will now first attempt to find an
existing context class, and only create a new context class if a context is not found.
- `ActiveInteractor::Organizer.organize` …
> generate v1.0.0-beta.1 release

- lib/active_interactor.rb
- lib/active_interactor/config.rb
- lib/active_interactor/railtie.rb
- lib/rails/generators/active_interactor/templates/initializer.erb
- spec/active_interactor/config_spec.rb
- spec/active_interactor_spec.rb
Created the `ActiveInteractor::Railtie` and `ActiveInteractor::Config` objects
- resolves #99 
- `ActiveInteractor::Config`
- `ActiveInteractor.config`
- `ActiveInteractor.configure`
- `ActiveInteractor::Railtie`
- `ActiveInteractor.logger` is now part of `ActiveInteractor.config`
- `ActiveInteractor.logger=`
> ActiveInteractor::Railtie

- README.md
- lib/active_interactor.rb
- lib/active_interactor/config.rb
- lib/active_interactor/rails.rb
- lib/active_interactor/rails/config.rb
- lib/active_interactor/railtie.rb
- lib/rails/generators/active_interactor.rb
- lib/rails/generators/active_interactor/application_interactor_generator.rb
- lib/rails/generators/active_interactor/install_generator.rb
- lib/rails/generators/active_interactor/templates/initializer.erb
- lib/rails/generators/interactor/context/rspec_generator.rb
- lib/rails/generators/interactor/context/test_unit_generator.rb
- lib/rails/generators/interactor/context_generator.rb
- lib/rails/generators/interactor/interactor_generator.rb
- lib/rails/generators/interactor/organizer_generator.rb
- lib/rails/generators/interactor/rspec_generator.rb
- lib/rails/generators/interactor/test_unit_generator.rb
- spec/active_interactor/config_spec.rb
- spec/active_interactor/rails/config_spec.rb
Various improvements and rails configuration options
- resolves #96
- `ActiveInteractor::Rails`
- `ActiveInteractor::Rails::Config`
- `ActiveInteractor::Config#rails`
- various generator fixes
> various rails related improvements

- CHANGELOG.md
- lib/active_interactor/version.rb
generate v1.0.0-beta.2 release
- see #95
- see #96
- see #97
- see #99
- #102 `ActiveInteractor::Config`
- #102 `ActiveInteractor.config`
- #103 `ActiveInteractor::Rails`
- #103 `ActiveInteractor::Rails::Config`
- #102 `ActiveInteractor::Railtie`
- #105 interactor, organizer, and context generators now accept context_attributes
as arguments.
- #102 `ActiveInteractor.logger` is now part of `ActiveInteractor.config`
- #104 Interactor generators will no longer generate separate context classes for
interactors if `ActiveInteractor.config.rails.generate_context_classes` is set to `false`
- #103 various generator fixes
- #102 `ActiveInteractor.logger=` use `ActiveInteractor.config.logger=` instead
> generate v1.0.0-beta.2 release

- .github/workflows/deploy.yml
Remove the deploy step Publish to GPR
> remove Publish to GPR

- lib/active_interactor/interactor.rb
- lib/active_interactor/interactor/perform_options.rb
- lib/active_interactor/interactor/worker.rb
- spec/active_interactor/interactor/worker_spec.rb
Added options to interactor perform methods.
- `ActiveInteractor::Interactor::PerformOptions`
- `ActiveInteractor::Interactor.perform` now takes options
> perform options for interactors

- CHANGELOG.md
- lib/active_interactor/version.rb
generate the v1.0.0-beta.3 release
- [x Contains Tests
- #109 `ActiveInteractor::Organizer.parallel`
- #109 `ActiveInteractor::Organizer.perform_in_parallel`
- #109 `ActiveInteractor::Context::Base#merge`
- #110 `ActiveInteractor::Interactor::PerformOptions`
- #110 `ActiveInteractor::Interactor.perform` now takes options
> generate v1.0.0-beta.3 release

- README.md
Update README to indicate the project is in a beta and link to stable docs.
> small update to README.md to indicate the project is in beta

- CHANGELOG.md
- lib/active_interactor/version.rb
generate the v1.0.0-beta.4 release
- #114 `ActiveInteractor::Organizer::InteractorInterface`
- #114 `ActiveInteractor::Organizer::InteractorInterfaceCollection`
- #115 `ActiveInteractor::Interactor#options`
- #115 `ActiveInteractor::Interactor#with_options`
- #115 `ActiveInteractor::Interactor::PerformOptions#skip_each_perform_callbacks`
- #115 `ActiveInteractor::Interactor::Worker#execute_perform` and `#execute_perform!` no longer accept arguments,
use `ActiveInteractor::Interactor#with_options` instead.
- #115 `ActiveInteractor::Organizer` can now skip `each_perform` callbacks with
the option `skip_each_perform_callbacks`
- #115 `ActiveInteractor::Interactor#execute_rollback`
- #115 `ActiveInteractor::Interactor::Worker#run_callbacks`
> generate the v1.0.0-beta.4 release

- .github/workflows/deploy.yml
- README.md
small fixes for readme and deploy scripts
> small fixes for readme and deploy scripts

- CHANGELOG.md
- README.md
- lib/active_interactor/version.rb
generate the v1.0.0-beta.5 release
- #122 `ActiveInteractor::Rails::Railtie`
- #122 `ActiveInteractor::Rails.config`
- #122 `ActiveInteractor::Rails.configure`
- #122 `ActiveInteractor::Railtie` use `ActiveInteractor::Rails::Railtie` instead
- #122 `ActiveInteractor::Config#rails` use `ActiveInteractor::Rails.configure` instead
> generate the v1.0.0-beta.5 release

- CHANGELOG.md
- README.md
- lib/active_interactor/version.rb
generate the v1.0.0-beta.6 release
- #124 `ActiveInteractor::Context::Status`
- #124 `ActiveInteractor::Rails::ActiveRecord`
- #124 Abstracted status methods from `ActiveInteractor::Context::Base`
into `ActiveInteractor::Context::Status`
> generate the v1.0.0-beta.6 release

- CHANGELOG.md
- README.md
- lib/active_interactor/version.rb
generate the v1.0.0-beta.7 release
- #127 `ActiveInteractor::Rails::Models`
- #127 #126 `act_as_context` not working
- #127 `ActiveInteractor::Rails::ActiveRecord`
> generate the v1.0.0-beta.7 release

- spec/spec_helper.rb
- spec/support/coverage.rb
- spec/support/coverage/reporters.rb
- spec/support/coverage/reporters/codacy.rb
- spec/support/coverage/reporters/simple_cov.rb
- spec/support/coverage/runner.rb
fix coverage reporting for codeclimate
> fix coverage reporting for codeclimate

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/active_interactor/version.rb
generate the v1.0.0 release
- resolves #113 
- `ActiveInteractor::Config`
- `ActiveInteractor::Configurable`
- `ActiveInteractor::Context::Attributes#merge!`
- `ActiveInteractor::Context::Base#merge`
- `ActiveInteractor::Context::Loader`
- `ActiveInteractor::Context::Status`
- `ActiveInteractor::Error::InvalidContextClass`
- `ActiveInteractor::Models`
- `ActiveInteractor::Organizer::Callbacks`
- `ActiveInteractor::Organizer::InteractorInterface`
- `ActiveInteractor::Organizer::InteractorInterfaceCollection`
- `ActiveInteractor::Organizer::Organize`
- `ActiveInteractor::Organizer::Perform`
- `ActiveInteractor::Interactor::Context.contextualize_with`
- `ActiveInteractor::Interactor::Context#context_fail!`
- `ActiveInteractor::Interactor::Context#context_rollback!`
- …
> generate the v1.0.0 release

- README.md
update readme to require 'active_interactor'
> update readme to require 'active_interactor'

- Gemfile.lock
- README.md
- activeinteractor.gemspec
- lib/active_interactor.rb
include links in docs and update readme and spec description
> include links in docs and update readme and spec description

- CHANGELOG.md
- lib/active_interactor/context/attributes.rb
- lib/active_interactor/context/base.rb
- lib/active_interactor/interactor/context.rb
- spec/active_interactor/context/base_spec.rb
Implement the `ActiveModel::Attributes` API on `ActiveInteractor::Context::Base`
- see #137
- `ActiveInteractor::Context::Attributes#attribute?`
- `ActiveInteractor::Context::Attributes#has_attribute?`
- `ActiveInteractor::Context::Base#attribute_missing`
- `ActiveInteractor::Context::Base#attribute_names`
- `ActiveInteractor::Context::Base#method_missing`
- `ActiveInteractor::Context::Base#respond_to?`
- `ActiveInteractor::Context::Base#respond_to_without_attributes?`
- `ActiveInteractor::Context::Base.attribute`
- `ActiveInteractor::Context::Base.attribute_missing`
- `ActiveInteractor::Context::Base.attribute_names`
- `ActiveInteractor::Context::Base.method_missing`
- `ActiveInteractor::Context::Base.respond_to?`
- `ActiveInteractor::Context::Base.respond_to_without_attributes?`
- …
> Implement ActiveModel::Attributes on context

- .github/workflows/ci.yml
fix code climate coverage reporting
> fix code climate coverage reporting

- .github/workflows/ci.yml
> remove print-env action

- .github/workflows/ci.yml
For the time being we're going to remove code climate test coverage reporting until a proven solution that works with github actions is released.  We have reporting via Codacy so its not a huge loss at the moment.
> remove code climate test coverage reporting

- lib/active_interactor/context/attributes.rb
- lib/active_interactor/context/base.rb
- lib/active_interactor/interactor/context.rb
- spec/integration/a_basic_interactor_spec.rb
Add spec to ensure default attributes are working
- see #149
> #149: add spec to ensure functionality is present

- lib/active_interactor/interactor/context.rb
move `context_attribute` documentation to appropriate method.
> move documentation to approriate method

- CHANGELOG.md
- Gemfile.lock
- lib/active_interactor/context/attributes.rb
- lib/active_interactor/context/base.rb
- lib/active_interactor/interactor/context.rb
- lib/active_interactor/version.rb
generate the v1.0.1 release
- resolves #137 
- resolves #149 
- `ActiveInteractor::Context::Attributes#attribute?`
- `ActiveInteractor::Context::Attributes#has_attribute?`
- `ActiveInteractor::Context::Base.attribute`
- `ActiveInteractor::Context::Base.attribute_missing`
- `ActiveInteractor::Context::Base.attribute_names`
- `ActiveInteractor::Context::Base.method_missing`
- `ActiveInteractor::Context::Base.respond_to?`
- `ActiveInteractor::Context::Base.respond_to_without_attributes?`
- `ActiveInteractor::Context::Base#attribute_missing`
- `ActiveInteractor::Context::Base#attribute_names`
- `ActiveInteractor::Context::Base#method_missing`
- `ActiveInteractor::Context::Base#respond_to?`
- `ActiveInteractor::Context::Base#respond_to_without_attributes?`
- …
> generate v1.0.1 release

- .github/ISSUE_TEMPLATE/bug_report.md
- ...
- ...
- ...
- ...
- ...
- ...
- ...
> use the unverified label instead of needs-verification

- README.md
- ...
- ...
- ...
- ...
- ...
- ...
- ...
> add documentation badges to README

- README.md
> add the value prop to README

- lib/active_interactor/rails/orm/dynamoid.rb
- lib/active_interactor/rails/orm/mongoid.rb
Add support for Mongoid and Dynamoid ORMs
- see #156 
- see #158
- ORM support for `Dynamoid`
- ORM support for `Mongoid`
> Support more orms

- CHANGELOG.md
- Gemfile.lock
- lib/active_interactor/version.rb
generate v1.0.2 release
- resolves #129 
- resolves #136 
- resolves #156 
- resolves #158
- Support for `Dynamoid` ORM
- Support for `Mongoid` ORM
- `ActiveInteractor::Models#acts_as_context` no longer includes `ActiveModel::Validations`
- `ActiveInteractor::Models#acts_as_context` now includes `ActiveInteractor::Context::Attributes`
- `ActiveInteractor::Models::InstanceMethods#merge!`
> generate v1.0.2 release

- spec/spec_helper.rb
- ...
- ...
- ...
- ...
- ...
- ...
- ...
> fix codacy coverage reporting

- CHANGELOG.md
- Gemfile.lock
- lib/active_interactor/context/errors.rb
- lib/active_interactor/context/status.rb
- lib/active_interactor/version.rb
generate the v1.0.3 release
- resolves #168 
- resolves #169
- `ActiveInteractor::Context::Errors`
- `ActiveInteractor::Context::Status#resolve`
- #168  `#classify` is called on const arguments
- #169 If some of the interactors of the organizer fail error message is not persisted.
> generate the v1.0.3 release

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
- ...
- ...
- ...
- ...
- ...
- ...
- ...
> fix codacy coverage

- CHANGELOG.md
- lib/active_interactor.rb
- lib/active_interactor/config.rb
- lib/active_interactor/logging.rb
- lib/rails/generators/templates/active_interactor.erb
- spec/active_interactor/config_spec.rb
- spec/active_interactor_spec.rb
Implement `ActiveInteractor::NextMajorDeprecator`
- see #177 
- `ActiveInteractor::NextMajorDeprecator`
- `ActiveInteractor::Config#silence_deprecation_warnings`
> #177 add `NextMajorDeprecator`

- CHANGELOG.md
- Gemfile.lock
- lib/active_interactor/version.rb
Generate the v1.0.4 release
- resolves #184 
- #184 `ActiveInteractor::Context::Base#fail!` error message gets pupulated 3 times with the same message.
> generate the v1.0.4 release

- CHANGELOG.md
- lib/active_interactor.rb
- lib/active_interactor/state/manager.rb
- lib/active_interactor/state/mutation.rb
- lib/active_interactor/state/status.rb
- spec/active_interactor/state/manager_spec.rb
Added `ActiveInteractor::State`
- see #135 
- resolves [AI-4](https://aaronmallen.atlassian.net/browse/AI-4)
- `ActiveInteractor::State`
> [AI-4] added ActiveInteractor::State

- FUNDING.yml
- ...
- ...
- ...
- ...
- ...
- ...
- ...
> add funding yml

- CHANGELOG.md
- lib/active_interactor.rb
- lib/active_interactor/result.rb
- spec/active_interactor/result_spec.rb
Add `ActiveInteractor::Result`
- resolves [AI-5]
- `ActiveInteractor::Result`
> [AI-5]: add ActiveInteractor::Result

- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
Add codacy coverage reporting to the build.
- resolves [AI-16]
[AI-16]: https://aaronmallen.atlassian.net/browse/AI-16
> Add Codacy coverage reporting

- .github/workflows/ci.yml
- ...
- ...
- ...
- ...
- ...
- ...
- ...
> add commit uuid

- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
- ...
- ...
- ...
- ...
- ...
- ...
- ...
> [AI-16] Chore/revert codacy reporter

- lib/active_interactor/interactor/perform.rb
refactor `ActiveInteractor::Interactor::Perform#deep_dup` to behave like a dup method.
- [AI-19]
- refactored `ActiveInteractor::Interactor::Perform#deep_dup` to behave like a `dup` method.
[AI-19]: https://aaronmallen.atlassian.net/browse/AI-19
> [AI-19] refactor deep_dup to behave like dup method

- .github/workflows/ci.yml
- ...
- ...
- ...
- ...
- ...
- ...
- ...
> attempt to run ci on approriate branches

- lib/active_interactor.rb
- lib/active_interactor/state.rb
- spec/active_interactor/state_spec.rb
Implement `ActiveInteractor::State`
- [AI-44]
- `ActiveInteractor::State`
[AI-44]: https://aaronmallen.atlassian.net/browse/AI-44
> [AI-44] added ActiveInteractor::State

- lib/active_interactor.rb
- lib/active_interactor/interactor/perform.rb
- lib/active_interactor/result.rb
- spec/active_interactor/result_spec.rb
Implement the `ActiveInteractor::Result`
- [AI-45]
- `ActiveInteractor::Result`
[AI-45]: https://aaronmallen.atlassian.net/browse/AI-45
> [AI-45] ActiveInteractor::Result

- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
implement codacy coverage reporting.
> implement codacy coverage reporting

- lib/active_interactor/context/attributes.rb
- spec/active_interactor/context/base_spec.rb
ensure attributes defined on the context are accessible
- see #200 
- `ActiveInteractor::Context::Attributes#[]` to check `ActiveInteractor::Context::Attributes#attributes` for values
> [AI-1] ensure attributes defined on the context are accessible

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/active_interactor/context/attributes.rb
- lib/active_interactor/version.rb
Generate the v1.0.5 release
- resolves #200
- #200 Context attributes assigned in interactor not accessible as element within interactor
> generate v1.0.5 release

- activeinteractor.gemspec
> #251 ensure ActiveInteractor is loaded

- activeinteractor.gemspec
This reverts commit 59fe171
- see #251
> Revert " #251 ensure ActiveInteractor is loaded"

- .github/dependabot.yml
remove bundler from dependabot config
- resolves #251
> #251 remove bundler from dependabot config

- .github/workflows/ci.yml
Ensure coverage is only reported when `CC_TEST_REPORTER_ID` has a value
- resolves #249
> #249 only report coverage if CC_TEST_REPORTER_ID is present

- .github/workflows/ci.yml
ensure correct branch name is returned to codeclimate
> ensure correct branch name is returned to codeclimate

- SECURITY.md
> updated SECURITY.md

- .github/ISSUE_TEMPLATE/security_report.md
- SECURITY.md
added the security_report issue template
> added the security_report issue template

- lib/active_interactor.rb
- lib/active_interactor/interactor/state.rb
- spec/active_interactor/interactor/state_spec.rb
adds the state object
- see #264 
- `ActiveInteractor::Interactor::State`
> added ActiveInteractor::Interactor::State

- lib/active_interactor/context/attributes.rb
- spec/integration/a_basic_organizer_spec.rb
cherry pick @mohameddiaa27 changes to main
- see #277
- see #267
- #277
> cherry pick @mohameddiaa27 changes to main

- CHANGELOG.md
- Gemfile.lock
- lib/active_interactor/version.rb
Generate the v1.1.1 release
- resolves #277 
- #267  Allow default attributes to propagate to sibling/child interactors
> generate the v1.1.1 release

- lib/active_interactor.rb
- lib/active_interactor/interactor/result.rb
- lib/active_interactor/interactor/state.rb
- spec/active_interactor/interactor/result_spec.rb
- spec/active_interactor/interactor/state_spec.rb
Added `ActiveInteractor::Interactor::Result`
- see #268 
- `ActiveInteractor::Interactor::Result`
- `ActiveInteractor::Interactor::State#rolled_back`
- `ActiveInteractor::Interactor::State#rolled_back!`
> added ActiveInteractor::Interactor::Result

- .github/workflows/lint.yml
- CONTRIBUTING.md
- Gemfile
- HUMANS.md
- README.md
- bin/rubocop
- Update collaborative documents for contributors
- simplify linting
> various document updates and build improvements

- lib/active_interactor.rb
- lib/active_interactor/config.rb
- lib/active_interactor/deprecation.rb
- spec/active_interactor/config_spec.rb
- spec/active_interactor/deprecation_spec.rb
Provide an api for deprecation logging
- see #287 
- `ActiveInteractor::Config#deprecation_debugging`
- `ActiveInteractor::Config#silence_deprecation_warnings`
- `ActiveInteractor::Deprecation`
> Deprecation

- Gemfile.lock
- activeinteractor.gemspec
- lib/active_interactor/context/errors.rb
Ensure compatibility with `ActiveModel` 6.1
- see #299 
- `ActiveModel` and `ActiveSupport` v6.1 will be the highest supported version for `ActiveInteractor` v1.1.x
- `ActiveInteractor::Context::Error` compatibility with `ActiveModel` v6.1
> ensure compatibility with activemodel 6.1

- .rubocop.yml
- lib/active_interactor/version.rb
various rubocop fixes
- resolves #303
- resolves #304
> Rubocop fixes

- .github/workflows/deploy.yml
- .yardopts
- Gemfile
- bin/prepare-deploy
- lib/active_interactor.rb
- spec/spec_helper.rb
> Build improvements

- lib/active_interactor.rb
- lib/active_interactor/attribute.rb
- spec/active_interactor/attribute_spec.rb
Add Attribute
- `ActiveInteractor::Attribute`
> Add Attribute

- lib/active_interactor.rb
- lib/active_interactor/attribute_set.rb
- spec/active_interactor/attribute_set_spec.rb
Add AttributeSet
- `ActiveInteractor::AttributeSet`
> Attribute set

- lib/active_interactor.rb
- lib/active_interactor/attribute_set.rb
- spec/active_interactor/attribute_set_spec.rb
Create AttributeSet to manage a collection of Attributes
- `ActiveInteractor::AttributeSet`
> Add AttributeSet

- lib/active_interactor.rb
- lib/active_interactor/attribute_set.rb
- lib/active_interactor/context.rb
- spec/active_interactor/context_spec.rb
Add context object
- `ActiveInteractor::Context`
- `ActiveInteractor::AttributeSet#attribute?` will now handle properly `String` arguments
- `ActiveInteractor::AttributeSet#get_attribute` will now handle properly `String` arguments
> Add Context Object

- .rubocop/rspec.yml
- lib/active_interactor.rb
- lib/active_interactor/interactor.rb
- spec/integration/a_basic_successful_interactor_spec.rb
- spec/spec_helper.rb
- spec/support/helpers/factories.rb
- spec/support/spec_helpers.rb
Add a basic integration spec for interactors
- `ActiveInteractor::Interactor`
> Add a basic integration spec for interactors

- .github/workflows/build_gem.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .github/workflows/upload_sarif.yml
- ...
- ...
- ...
- ...
- ...
- ...
- ...
> Abstract github actions into individual files.

- .github/dependabot.yml
- .github/workflows/build_gem.yml
- .github/workflows/test.yml
- .github/workflows/upload_sarif.yml
- ...
- ...
- ...
- ...
- ...
- ...
- ...
> Abstract individual actions into reusable workflows

- .github/workflows/build_gem.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- ...
- ...
- ...
- ...
- ...
- ...
- ...
> Fix workflow files

- CHANGELOG.md
- lib/active_interactor/version.rb
generate v1.1.4 release
- #340 Bump activemodel and activesupport to 6.1.4.6
> generate v1.1.4 release

- CHANGELOG.md
Generate the v1.1.5 release
- #344 Bump activemodel and activesupport to v7.0.2.3
> generate the v1.1.5 release

- CHANGELOG.md
- lib/active_interactor/version.rb
Generate the v1.1.6 release
- #344 Bump activemodel and activesupport to v7.0.2.3
> generate v1.1.6 release

- CHANGELOG.md
- SECURITY.md
- lib/active_interactor/interactor/callbacks.rb
- lib/active_interactor/organizer/callbacks.rb
- lib/active_interactor/organizer/interactor_interface.rb
- lib/active_interactor/version.rb
Generate the v1.2.0 release
- #350 
- `ActiveInteractor::Base.defer_after_callbacks_when_organized`
- `ActiveInteractor::Organizer::Base.after_all_perform`
- `ActiveInteractor::Organizer::Base.around_all_perform`
- `ActiveInteractor::Organizer::Base.before_all_perform`
> generate the v1.2.0 release

- CHANGELOG.md
- lib/active_interactor/version.rb
Generate the v1.1.7 release
- #358 Typo in generator template name
> generate the v1.1.7 release

- CHANGELOG.md
- lib/active_interactor/version.rb
Generate the v1.2.1 release
- #358 Typo in generator template name
> generate the v1.2.1 release

- CHANGELOG.md
- lib/active_interactor/version.rb
- #366 
- Fixes a minor timing issue for when deferred after_perform callbacks are run.
> generate v1.2.2 release

- .github/workflows/build_gem.yml
- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .github/workflows/upload_sarif.yml
- ...
- ...
- ...
- ...
- ...
- ...
- ...
> fix the build
