lib/active_interactor.rb, spec/active_interactor/organizer_spec.rb
fixed #13 NameError (uninitialized constant ActiveInteractor::Organizer)
fixes #13
=> NameError (uninitialized constant ActiveInteractor::Organizer)

CHANGELOG.md, README.md, lib/active_interactor/context.rb, lib/active_interactor/context/attributes.rb, lib/active_interactor/context/errors.rb, lib/active_interactor/interactor.rb, lib/active_interactor/interactor/context.rb, spec/support/shared_exaples/context_lint.rb, spec/support/shared_exaples/interactor_lint.rb
Added the ability to alias context attributes
=> Alias context attributes

README.md, lib/active_interactor/context/attributes.rb
=> fix small typo in README

Gemfile.lock, README.md, lib/active_interactor.rb, lib/active_interactor/context.rb, lib/active_interactor/error.rb, lib/active_interactor/interactor.rb, lib/active_interactor/interactor/worker.rb, lib/active_interactor/version.rb, spec/active_interactor/interactor/worker_spec.rb, spec/active_interactor/organizer_spec.rb
* Created the `ActiveInteractor::Error` module
* Deprecated `ActiveInteractor::Context::Failure` in favor of `ActiveInteractor::Error::ContextFailure`
=> ActiveInteractor::Error

Gemfile.lock
Here is everything you need to know about this update. Please take a good look at what changed and the test results before merging this pull request.
<details>
<summary>Release Notes</summary>
<h4><a href="https://github.com/colszowka/simplecov/releases/tag/v0.17.0">0.17.0</a></h4>
<blockquote><p>Maintenance release with nice convenience features and important bugfixes.<br>
Notably this <strong>will be the last release to support ruby versions that have reached their end of life</strong>. Moving forward official CRuby support will be 2.4+ and JRuby support will be 9.1+. Older versions might still work but no guarantees.</p>
<h2>Enhancements</h2>
<ul>
<li>Per default filter hidden files and folders. See <a href="https://bounce.depfu.com/github.com/colszowka/simplecov/pull/721">#721</a> …
=> Update simplecov: 0.16.1 → 0.17.0 (major) 

CHANGELOG.md, Gemfile.lock, lib/active_interactor/version.rb
With this release we will be placing version 0.1 of the gem into maintenance mode. All new features will go into v1.0.0 of the gem and only bug fixes will be done on 0.1
- [#45] Lowered method complexity and enforced single responsibility
- [#48] Update simplecov: 0.16.1 → 0.17.0 (major)
- [#51] Update rake: 12.3.2 → 12.3.3 (patch)
=> v0.1.6 release

lib/active_interactor/rails/config.rb, lib/rails/generators/active_interactor/application_interactor_generator.rb, lib/rails/generators/active_interactor/templates/initializer.erb, lib/rails/generators/interactor/interactor_generator.rb, lib/rails/generators/interactor/organizer_generator.rb, spec/active_interactor/rails/config_spec.rb
added configuration option for context generators
- resolves #95
- `ActiveInteractor::Rails::Config#generate_context_classes`
- Interactor generators will no longer generate separate context classes for interactors if `ActiveInteractor.config.rails.generate_context_classes` is set to `false`
=> #95 added configuration option for context generators

lib/rails/generators/active_interactor.rb, lib/rails/generators/active_interactor/application_interactor_generator.rb, lib/rails/generators/active_interactor/templates/initializer.erb, lib/rails/generators/interactor/context/rspec_generator.rb, lib/rails/generators/interactor/context/test_unit_generator.rb, lib/rails/generators/interactor/context_generator.rb, lib/rails/generators/interactor/interactor_generator.rb, lib/rails/generators/interactor/organizer_generator.rb, lib/rails/generators/interactor/rspec_generator.rb, lib/rails/generators/interactor/templates/context.erb, lib/rails/generators/interactor/templates/interactor.erb, lib/rails/generators/interactor/templates/organizer.erb, lib/rails/generators/interactor/test_unit_generator.rb
Context generators will now accept a context attributes argument
- resolves #97 
- context_attributes arguments to interactor, organizer, and context generators
- skip-context argument to interactor, organizer, and context generators
=> #97 add context_attributes argument to context generators

lib/active_interactor/config.rb, lib/active_interactor/configurable.rb, lib/active_interactor/rails/config.rb, spec/active_interactor/config_spec.rb, spec/active_interactor/rails/config_spec.rb
Address duplication issues for configuration objects
- `ActiveInteractor::Configurable`
- `ActiveInteractor::Config::DEFAULTS` use `ActiveInteractor::Config.defaults` instead
- `ActiveInteractor::Rails::Config::DEFAULTS` use `ActiveInteractor::Rails::Config.defaults` instead
=> address duplication issues for configuration objects

README.md, lib/active_interactor/context/attributes.rb, lib/active_interactor/context/base.rb, lib/active_interactor/interactor/worker.rb, lib/active_interactor/organizer.rb, spec/active_interactor/context/base_spec.rb, spec/active_interactor/organizer_spec.rb, spec/integration/basic_integration_spec.rb
Implements parallel performance for organizers.
- resolves #35 
- `ActiveInteractor::Organizer.parallel`
- `ActiveInteractor::Organizer.perform_in_parallel`
- `ActiveInteractor::Context::Base#merge`
- `ActiveInteractor::Interactor::Worker#execute_perform` and `#execute_perform!` now take option arguments
=> Parallel interactor performance in organizers

README.md, lib/active_interactor/organizer.rb, lib/active_interactor/organizer/interactor_interface.rb, lib/active_interactor/organizer/interactor_interface_collection.rb, spec/active_interactor/organizer/interactor_interface_collection_spec.rb, spec/active_interactor/organizer/interactor_interface_spec.rb, spec/active_interactor/organizer_spec.rb, spec/integration/basic_integration_spec.rb
Allow organized interactors to be skipped based on conditional options
- resolves #36
- `ActiveInteractor::Organizer::InteractorInterface`
- `ActiveInteractor::Organizer::InteractorInterfaceCollection`
=> #36 Allow organized interactors to be skipped based on conditional options

spec/active_interactor/context/base_spec.rb
remove `after(:each)` in `context/base_spec`
- resolves #145
=> remove after(:each) in context/base_spec

CHANGELOG.md, lib/active_interactor/context/loader.rb, lib/active_interactor/interactor/context.rb, lib/active_interactor/organizer/interactor_interface.rb, lib/rails/generators/templates/organizer.erb, spec/active_interactor/base_spec.rb
Use `camelize` instead of `classify` to `safe_constantize` class names to prevent singularization of passed `Symbol` or `String` arguments.
- see #167
- see #168
- #168 `#classify` is called on const arguments
=> Use camelize instead of classify to safe_constantize

CHANGELOG.md, lib/active_interactor.rb, lib/active_interactor/context/attributes.rb, lib/active_interactor/context/base.rb, lib/active_interactor/context/errors.rb, lib/active_interactor/context/status.rb, lib/active_interactor/interactor/context.rb, lib/active_interactor/models.rb, spec/active_interactor/context/base_spec.rb, spec/integration/a_basic_organizer_spec.rb
Fix error persistence across context instances for organizers
- see #169 
- `ActiveInteractor::Context::Errors`
- `ActiveInteractor::Context::Status#resolve`
- #169 If some of the interactors of the organizer fail error message is not persisted.
=> [#169] Fix error persistence in organizers  

CHANGELOG.md, lib/active_interactor/context/errors.rb, spec/integration/a_basic_organizer_spec.rb
Ensure errors on a context are uniq
- see #184 
- #184 Context.fail! error message gets pupulated 3 times with the same message
=> Fix error message duplication

lib/active_interactor/result.rb
ensure we pass`include_private` to `respond_to?`
- fixes [AI-31]
- `respond_to?` is false for private `context` methods on `ActiveInteractor::Result`
[AI-31]: https://aaronmallen.atlassian.net/browse/AI-31
=> [AI-31] ensure we pass include_private to respond_to?

lib/active_interactor/organizer/perform.rb, spec/integration/an_organizer_with_failing_nested_organizer_spec.rb
Allow nested Organizers to fail/rollback parent organizer context
- see #243 
- Fail context in `ActiveInteractor::Organizer#perform_in_order` after nested failing organizer execution
- Extract `ActiveInteractor::Organizer#perform_in_order` logic to `ActiveInteractor::Organizer#execute_and_merge_contexts` to avoid code climate method-complexity offense
- #243 Failing Nested Organizers to fail/rollback parent organizer
=> Allow nested Organizers to fail parent organizer context

lib/active_interactor/context/attributes.rb, spec/integration/a_basic_organizer_spec.rb
Undefined optional attributes not being updated (on external context) from internal interactors.
- https://github.com/aaronmallen/activeinteractor/issues/242
- `ActiveInteractor::Context::Attributes#[]=` to set Hash attributes in `ActiveInteractor::Context::Attributes#attributes`
- `ActiveInteractor::Context::Attributes#merge!` to use attributes from both `ActiveInteractor::Context::Attributes#attributes` and `ActiveInteractor::Context::Attributes#to_h`
- https://github.com/aaronmallen/activeinteractor/issues/242 Optional attributes are always null
=> Allow undefined optional attributes to be set internally

lib/active_interactor/organizer/interactor_interface.rb, lib/active_interactor/organizer/perform.rb, spec/active_interactor/organizer/interactor_interface_spec.rb, spec/integration/an_organizer_with_options_callbacks_spec.rb
Allow developers to add in place callbacks to be able to update context in order to be able to resuse interactors in different contexts. 
- see https://github.com/aaronmallen/activeinteractor/issues/247
- `ActiveInteractor::Organizer::InteractorInterface#execute_inplace_callback`
- `ActiveInteractor::Organizer#execute_and_merge_contexts`
=> Support in place Callbacks

lib/active_interactor/version.rb, spec/active_interactor_spec.rb
reintroduce `ActiveInteractor::VERSION` to ensure backwards compatibility
=> reintroduce ActiveInteractor::VERSION to ensure backwards compatibility

lib/active_interactor/context/attributes.rb, spec/integration/a_basic_organizer_spec.rb
* Add test cases to cover expected behavior for context default attributes.
* Ensure that default attributes are correctly accessible in all interactors pending to perform.
- see https://github.com/aaronmallen/activeinteractor/issues/277.
- `ActiveInteractor::Context::Attributes#merge!` to set attributes in both `ActiveInteractor::Context::Attributes#attributes` and `ActiveInteractor::Context::Attributes#table`
- `ActiveInteractor::Context::Attributes#initialize` to set attributes in both `ActiveInteractor::Context::Attributes#attributes` and `ActiveInteractor::Context::Attributes#table`
- https://github.com/aaronmallen/activeinteractor/issues/277 Allow default attributes to propagate to sibling/child interactors
=> Allow default attributes to propagate to child/sibling interactors

SECURITY.md
Drop bugfix support in `1.0.x` in favor of addressing them in `1.1.x`.  The changes between `1.0` and `1.1` are pretty minimal so asking consumers to update to the next minor isn't unreasonable.
=> drop bug support for 1.0.x

lib/active_interactor/interactor/callbacks.rb, lib/active_interactor/interactor/worker.rb, spec/support/shared_examples/a_class_with_interactor_callback_methods_example.rb
Provide a way to hook into interactor failures.
- see #217 
- `ActiveInteractor::Base.before_failure`
- Interactors will now emit an `ActiveSupport::Notification` named `interactor failure` on interactor failure.
=> #217 interactor failure hooks

lib/active_interactor/interactor/result.rb, spec/active_interactor/interactor/result_spec.rb
Add `method_missing` to `ActiveInteractor::Interactor::Result` instead of using `delegate_missing_to`
`OpenStruct` does not actually return `true` for `respond_to` when passing in a variable writer method so `delegate_missing_to` fails in this regard.
- see #270
=> #270 Result method_missing

lib/active_interactor/context/status.rb
deprecate `ActiveInteractor::Context::Status`
- see #271 
- `ActiveInteractor::Context::Status`
=> #271 deprecate ActiveInteractor::Context::Status

lib/active_interactor/context/errors.rb
deprecate `ActiveInteractor::Context::Errors`
- see #275 
- `ActiveInteractor::Context::Errors`
=> #275 deprecate ActiveInteractor::Context::Errors

lib/active_interactor/attribute_set.rb, spec/active_interactor/attribute_set_spec.rb
AttributeSet is meant to be a collection of Attributes. Therefor the class can afford to be coupled to the Attribute class for easier use.
- `ActiveInteractor::AttributeSet#add`
- `ActiveInteractor::AttributeSet#attribute?`
- `ActiveInteractor::AttributeSet#attribute_names`
- `ActiveInteractor::AttributeSet#clear!`
- `ActiveInteractor::AttributeSet#empty?`
- `ActiveInteractor::AttributeSet#get_attribute`
- `ActiveInteractor::AttributeSet#get_value`
- `ActiveInteractor::AttributeSet.new` now takes a splat of `ActiveInteractor::Attribute`
- `ActiveInteractor::AttributeSet#[]=`
- `ActiveInteractor::AttributeSet#each`
- `ActiveInteractor::AttributeSet#each_with_object`
- `ActiveInteractor::AttributeSet#fetch_value`
- `ActiveInteractor::AttributeSet#key?`
- …
=> Refactor AttributeSet

activeinteractor.gemspec
Bump activemodel and activesupport to 6.1.4.4
Bump activemodel and activesupport to 6.1.4.4
activemodel and activesupport dependencies from <= 6.1 to <= 6.1.4.4
=> Bump activemodel and activesupport to 6.1.4.4

activeinteractor.gemspec
After updating Rails version to 6.1.4.6 we have new dependencies activemodel and activesupport.
Bump activemodel and activesupport to 6.1.4.6
activemodel and activesupport dependencies from <= 6.1.4.4 to <= 6.1.4.6
=> Bump activemodel and activesupport to 6.1.4.6

.rubocop/style.yml, activeinteractor.gemspec, spec/support/shared_examples/a_class_with_interactor_callback_methods_example.rb
To support Ruby on Rails 7, bump activemodel and activesupport to 7.0.2.3
- Bump activemodel and activesupport to 7.0.2.3
- Disable Layout/BlockAlignment in RuboCop
=> Bump activemodel and activesupport to 7.0.2.3

lib/active_interactor/interactor/worker.rb, lib/active_interactor/organizer/perform.rb
`all_perform` is a redundant set of callbacks and is entirely enveloped by the Organizer's `perform` callbacks. This change moves the execution of the deferred callbacks to after `perform` rather than `all_perform` to better match the intent of the `defer_after_callbacks_when_organized` attribute.
The impact of this should be very minimal as, in both cases, the callbacks are still deferred until after all nested interactors have finished. 
- ~[ ] Contains Documentation~ It's a bug fix for logic that is already documented.
- ~[ ] Contains Tests~ Left tests unmodified to validate it is not a breaking change
- ~[ ] Contains Breaking Changes~ Does not.
- Fixes a minor timing issue for when deferred `after_perform` callbacks are run.
=> Defer until after `perform` instead of `all_perform`
